#!/usr/bin/env bash

set -euo pipefail

function find_defined_tags() {
  local dotfiles_dirs=${DOTFILES_DIRS:="${HOME}/.dotfiles"}
  local tags=()
  for dotfiles_dir in $dotfiles_dirs; do
    for tag_dir in $(find "${dotfiles_dir}" -maxdepth 1 -name 'tag-*'); do
      tags+=("${tag_dir##*/tag-}")
    done
  done
  echo -n "${tags[@]}"
}

function write_rcrc() {
  echo -n "Checking for ~/.rcrc... "

  local defined_tags=$(find_defined_tags)
  local rcrc=${RCRC:="${HOME}/.rcrc"}

  if [ -e "$rcrc" ]; then
    echo "present"
    return
  fi

  echo "not found"
  echo
  echo "It looks like you don't have an .rcrc set up. You can silence this"
  echo "warning with:"
  echo
  echo "   touch ${rcrc}"
  echo
  echo "You should consider adding a line like the following one to the file"
  echo "to specify default tags for this instance:"
  echo
  echo "   TAGS=<tag>..."
  echo

  if [ -n "$defined_tags" ]; then
    echo "Configured tags: ${defined_tags}"
  fi
}

write_rcrc
