#!/usr/bin/env bash

# Exit immediately on error
set -e

LOCAL="${HOME}/.local"
FZF_HOME="${LOCAL}/lib/fzf"

install_fzf() {
  echo "Installing FZF…"
  git clone --depth 1 https://github.com/junegunn/fzf.git "$FZF_HOME"
  "${FZF_HOME}/install" --bin
  ln -s ../lib/fzf/bin/fzf "${LOCAL}/bin/fzf"
  echo "FZF installed"
}

if [ ! -d "$FZF_HOME" ]; then
  install_fzf
fi
