#!/usr/bin/env bash

# Exit immediately on error
set -euo pipefail

install_fzf() {
  echo -n "Checking for fzf... "

  local local="${HOME}/.local"
  local fzf_home="${local}/lib/fzf"
  if [ -d "$fzf_home" ]; then
    echo "present"
    return
  fi

  echo "not found, installing..."
  git clone --depth 1 https://github.com/junegunn/fzf.git "$fzf_home"
  "${fzf_home}/install" --bin
  ln -s ../lib/fzf/bin/fzf "${local}/bin/fzf"
  echo "Installed fzf"
}

install_fzf
