"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Author: Shawn Tice, with *lots* of help from the internet.

" Source a vimrc.d/ config file by name, without extension.
function! s:loadrc(file)
  let l:dir = expand("~/.vim/vimrc.d/")
  exec "source " . l:dir . a:file . ".vim"
endfunction

" Core: broadly applicable. In this section and the "Extras" section, order is
" significant. There aren't *many* dependencies, but there may be a few, and
" the files are generally sorted in descending order by importance.

call s:loadrc("settings")     " General settings
call s:loadrc("vundle")       " Load plugins
call s:loadrc("fzf")          " Fuzzy file finder
call s:loadrc("ctrl-p")       " General fuzzy finder, esp. for buffers
call s:loadrc("choosewin")    " Tmux-like window selection
call s:loadrc("restorepos")   " Restore cursor pos from last session
call s:loadrc("tabindent")    " Tab width default, tools to change
call s:loadrc("completion")   " Text completion
call s:loadrc("quickfix")     " Quickfix conveniences
call s:loadrc("commands")     " General commands
call s:loadrc("mappings")     " General mappings, leaders and more
call s:loadrc("colors")       " Color scheme, highlighting

" Extras: targeted to specific activities.

call s:loadrc("sneak")        " Like f/F but by bigram and with labels
call s:loadrc("matchit")      " Make % bounce between more things
call s:loadrc("sort")         " Sort lines quickly
call s:loadrc("slime")        " Interact with REPLs
call s:loadrc("custom-grep")  " Grep with temp grepprg replacement
call s:loadrc("rcedit")       " Edit vimrc
call s:loadrc("pencil")       " For writing markdown (and maybe other things)

" Context overrides: settings for a specific environment.

call s:loadrc("localrc")      " Override by host
call s:loadrc("projectrc")    " Override by project
