#!/usr/bin/env bash

# Create directories we know we'll need (if they don't exist already).
echo -n "Ensuring required directories exist... "
mkdir -p "${HOME}/.local/var"
mkdir -p "${HOME}/.vim/bundle"
echo "Done"
