#!/usr/bin/env bash

set -euo pipefail

run_brew_bundle() {
  local brewfile="${HOME}/.local/etc/Brewfile"
  local status_file="${brewfile}.lock.json"

  # Only continue if we found a Brewfile.
  [ ! -e "$brewfile" ] && exit

  echo -n "Checking Brewfile... "

  if [ ! -e "$status_file" -o "$brewfile" -nt "$status_file" ]; then
    echo "out of date, running brew bundle..."
    brew bundle --file "$brewfile"
    echo "Running bundle cleanup..."
    run_bundle_cleanup "$brewfile"
    touch "$status_file"
  else
    echo "up to date"
  fi
}

run_bundle_cleanup() {
  local brewfile="$1"
  brew bundle cleanup --file "$brewfile"
  if [ -n "${BREW_CLEANUP:-}" ]; then
    echo "Cleaning up..."
    brew bundle cleanup --file "$brewfile" --force
  else
    echo 'Rerun rcup with `BREW_CLEANUP=1 rcup` to apply'
  fi
}

run_brew_bundle
