#!/usr/bin/env bash

run_vundle() {
  # Install the vundle plugin if it's not already present.
  if [ ! -e "${HOME}/.vim/bundle/vundle" ]; then
    echo -n "Installing vundle... "
    mkdir -p "${HOME}/.vim/bundle"
    git clone 'https://github.com/gmarik/vundle.git' \
      "${HOME}/.vim/bundle/vundle"
    echo "Done"
  fi

  echo -n "Checking vim bundles... "

  status_file="${HOME}/.local/var/bundlesupdated"
  bundles_file="${HOME}/.local/etc/vimrc.bundles"
  bundle_local_file="${bundles_file}.local"
  if
    [ ! -e "${status_file}" ] || \
    [ "${bundles_file}" -nt "${status_file}" ] || \
    [ "${bundle_local_file}" -nt "${status_file}" ]
  then
    echo -n "Outdated, running vundle... "
    # -E stops vim from complaining about input not coming from a terminal.
    vim -Es -u "${bundles_file}" -c PluginUpdate -c qall'!'
    touch "${status_file}"
    echo "Done"
  else
    echo "Up to date"
  fi
}

run_vundle
