#!/usr/bin/env bash

set -euo pipefail

link_airport_cmd() {
  airport_src="/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport"
  airport_dst="${HOME}/.local/bin/airport"

  # Do nothing if the file doesn't exist on the platform.
  [ ! -e "$airport_src" ] && return

  echo -n "Checking for airport shortcut... "
  if [ ! -e "$airport_dst" ]; then
    echo -n "not found, linking..."
    ln -s "$airport_src" "$airport_dst"
    echo "done"
  else
    echo "present"
  fi
}

link_airport_cmd
